# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    env:
      DB_HOST: localhost
      DB_USER: root
      DB_PASS: root
      DB_NAME: esportcom_db

    steps:
    - uses: actions/checkout@v2
    - run: | 
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE esportcom_db;' -uroot -proot
        mysql -e 'use esportcom_db source ${{ github.workspace }}/database/database.sql;' -uroot -proot
        mysql -e 'SHOW TABLES FROM esportcom_db;' -uroot -proot 
    - name: Cancel previous runs of this workflow
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
